language: node_js
node_js:
  - '7'
os:
- linux
- osx
branches:
  only:
  - '/^v[0-9]/'
  - executable-build
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
before_deploy:
- yarn package
deploy:
- provider: releases
  api_key:
    secure: "nAD0ARFEPjZRjfJc987HvtAfNNvpnB71wVhUeYFgdN/5xjuj3BGjjXcBVEOYORDJdWRlQqi+bzh4Bf3aHggqEMoa7vrMqWKVf+af+q6Fb352DaAC4wynVn3VfsmfjVseEIpMPBGsyy3+4hg3Yxa/qkeQ5owGVVyszDXF4x8YWHCVsTZ6xWnU7Rjwzb5w2x5oEw79iXHE8uI1bw9RoObIHSnbzDw01WFjtCVJE5abXE8D9oeb3thF1lrAbU1hw6s4xgnAQnxK0WNpUEplvFL3/Tzrkg64pKRQpSEE8CkcPrrcQiptsaud0pBNqKip0tE/xzImfJviChoND5oDrcfmFsB3e2aajk4tQVQYDnIWCBCixWBs3RseQhkIuxhDbxUuQ8Hmzg1Hbp6cbQxmMRAOf7jTsFbCXrSA6ZgZNBxEHNqy4Hy3A+NcB9WFRw1neixWlx09gcujOp/cOX5FAGIHcjmjxbOPzNzWlN6SD719f4J7fHmayocs/GVLbzXSnONpXH+XmY8v/d7BNoPDo7O2arwQFJmZUKhzyEYMXibBY3n42Az00aSWqlHCLrHx/CfVHiM48MuLOlMRTHEcohAhlVbReVS7d7AGPeKw/iCGJNepfE7hY7fiHTGq8nPQTR3qrXQt7ZiF5OaAZ0FhF446SMvgkJgAAUdUB/ryTBHjkiA="
  file_glob: true
  file:
  - "deploy/*"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: serveradmin@octoblu.com
  skip_cleanup: true
  api_key:
    secure: "uTNCvXU1tSHoOeLUzMq9rJbWKl03SlwZ0FiI40iEZNkbVn9HDt/nLWH47KCdqVQJhmtRcWhUlqURtC18JGHNO84I+D18lYeklncwrf2nSbTjFTANrX9WHWTRhxZNAEuLfuPvukHJHUZUq1KyG8kvTVGTnL1Fq/spoJlU8xJdb+4i8oCAQenMo30N5SvGoD8CCK+RgTCJlpc23JTpvLmlz0XfMq2rknji0HU2RDU7TMzCF0Tpb/i4cMauIQOuLv6kqFxcz1ESxMz+nT54elFM0yy2Vi4w/0Ay2vonC+WPYCrLDxRBRsJZ4gHzYixH9raVDEtTb0dszmCnxx42KnZme1+rUIze1xiwpFTYwlh6Oswtg+ILpbTwmbK5rhqsSF0C16dnnyGomJoOi55DuL/wrx4Exsl9hyA+vaXxitXWOlcAYt0Mqct8E1SZrui6fLKKNzVrLEAfOsgIWKMqjxhtrtIQsJrOi4ach8mPqCCQXLsZ2NzSrC604hCWphDO4Asn+rdIsbImExz94TaCVqm9sZf9QtRLKy8gARC+u8S7v3pWn8SlwBgYGToGK710E/CBJleOQHT0XQwAedZ17aZ5cNKvHnqXWgVL3gof60Ww9G33zmGj5NUkV8lWYfmaM0Ct7j7jjrYUjCZFDVQs0GFRzxBeV8OPrEwk5Chebpkf5Kc="
  on:
    tags: true
