branches:
  only:
  - "/^v[0-9]/"
  - executable-build
env:
  global:
    secure: h2f1cQXkrQKmlhZBwZSpgQxYoQc/m8V2Gmuj1UVmW0Naw3AbRdJyoZo7bKRNt/16n4Y44QMEZjf9rk2nhdFX98vV/eW3s/anb2ngsVg/6H9Hc3W2LOye3AuY6TjjviVruOI8yfVwkTfnrtSdaqKBI4msrq/Wxcczah6qg6mQ/VG46DAvQwaB87WgH69tcL++7Lr/B70yPNzNqlHXwLmy4rOEHEs+6FUBpmHifjOT0m9CMFyExDEoORcLbAYl4l8z9Ibl8diWEAHfkZj5htm666dW8pwVULfSC+8mSLKkgmvOmDFNJs62lIn+XNjx74W1vlCdx5lYVhQraVqtxuS9rtGXAUqxp98dCeFyeiLjmyLHFw0PI4LYJwwA1N13i68Eh3IX8KW+7FW8zIcLa5Bq/eXlXPgNgM7Zx0G1LZzX7HoFgHAUYY1OBFAb3nOG9OM/Y+6ut2tcDNE6P6aj0TR8ilBgFTSqrFAmEgUt56DxAcA4zZiZswI382H0RP+09+JXJ+TJlQ7up87S2OdWHeHIeWJbbltfMkxp7sVJFTmAfSHAY4r7T3yLlIIemghtyyITEiK6MUyrYzorlzyrjG3Mu9kVd/wQZvjwVFyXQxLqeISlOeXKQBbWxwwHoVybMSxN7bzpQuSbriQLAT7Jrii/WPqsvDnCiax5k3p8MRitbKI=
matrix:
  include:
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/dockcross-node:linux-armv7
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/dockcross-node:linux-armv7 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/dockcross-node:linux-x86
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/dockcross-node:linux-x86 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
          '
  - os: linux
    dist: trusty
    language: shell
    sudo: required
    services:
    - docker
    install:
    - docker pull octoblu/dockcross-node:linux-x64
    script:
    - |
      docker run --rm --volume $PWD:/work \
        --env TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
        --env TRAVIS_BRANCH=$TRAVIS_BRANCH \
        --env MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN=$MESHBLU_CONNECTOR_UPLOADER_GITHUB_TOKEN \
        octoblu/dockcross-node:linux-x64 \
          bash -c 'export HOME=/tmp/cache \
            && meshblu-connector-pkger \
            && meshblu-connector-installer-debian \
            && meshblu-connector-uploader-github \
          '
